@extends('layouts.app')

@section('title', config('app.name'))
@section('description', 'Webnar - Your platform for webinars and live events.')

@section('content')
    @include('sections.hero-section')
    @include('sections.featured-in')
    @include('sections.what-is-graphology')
    @include('sections.card-with-image-left')
    @include('sections.what-you-will-learn')
    @include('sections.how-graphology-works')
    @include('sections.certificate-section')
    @include('sections.workshop-snapshots')
    @include('sections.graphology-steps')
    @include('sections.who-uses-graphology')

    @include('sections.video-testimonials')
    @include('sections.about-institute')
    @include('sections.meet-trainer')
    @include('sections.certified-graphologist')
    @include('sections.news-article')
    @include('sections.testimonials')
    @include('sections.value-stack')
    @include('sections.faq')
    @include('sections.end-section')
@endsection
